name: Windows

# Run CI only when a release is created, on changes to main branch, or any PR 
# to main. Do not run CI on any other branch. Also, skip any non-source changes 
# from running on CI
on:
  release:
    types: [created]
  push:
    branches: main
    paths-ignore:
    - 'docs/**'
    - 'examples/**'
    - '.gitignore'
    - 'README.rst'
    - '.github/workflows/manylinux.yml'
    - '.github/workflows/macos.yml'
    - '.github/workflows/sdl1-sdist.yml'
  pull_request:
    branches: main
    paths-ignore:
    - 'docs/**'
    - 'examples/**'
    - '.gitignore'
    - 'README.rst'
    - '.github/workflows/manylinux.yml'
    - '.github/workflows/macos.yml'
    - '.github/workflows/sdl1-sdist.yml'

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false  # if a particular matrix build fails, don't skip the rest
      # PyPy 7.3.3 has only win32 builds available (python 2.7, 3.6, and 3.7)
      # PyPy 7.3.4 and above does not have 32-bit builds, only 64-bit ones (python 3.7)
      # So we build with 7.3.3 for 32-bit builds, and 7.3.4+ for 64-bit builds
      matrix:
        # pyversion: ['3.5', '3.6', '3.7', '3.8', '3.9', 'pypy-2.7-v7.3.3', 'pypy-3.6-v7.3.3', 'pypy-3.7-v7.3.3', 'pypy-3.7']
        # disable all but one to save resources, since they are covered by appveyor windows builds.
        pyversion: ['3.5']
        arch: ['x64', 'x86']
        
        exclude:
          - pyversion: 'pypy-2.7-v7.3.3'
            arch: 'x64'
          - pyversion: 'pypy-3.6-v7.3.3'
            arch: 'x64'
          - pyversion: 'pypy-3.7-v7.3.3'
            arch: 'x64'
          - pyversion: 'pypy-3.7'
            arch: 'x86'

    steps:
    - uses: actions/checkout@v2.3.4

    # python 2.7 needs special treatment because it needs an old compiler to work
    # https://download.microsoft.com/download/7/9/6/796EF2E4-801B-4FC4-AB28-B59FBF6D907B/VCForPython27.msi
    # https://web.archive.org/web/20210106040224/https://download.microsoft.com/download/7/9/6/796EF2E4-801B-4FC4-AB28-B59FBF6D907B/VCForPython27.msi
    # - name: Setup MSBuild with MSVC v9.0
    #   if: matrix.pyversion == '2.7'
    #   run: |
    #     Invoke-WebRequest https://github.com/GeoNode/geonode-win-installer/raw/ffb76c7cbf1d6b4970c6c25f79c3c7682a3aa035/VCForPython27.msi -OutFile C:\VCForPython27.msi
    #     msiexec.exe /i "C:\VCForPython27.msi" /qn ALLUSERS=1

    # - name: Setup MSBuild with MSVC latest version
    #   if: matrix.pyversion != '2.7'
    #   uses: microsoft/setup-msbuild@v1.0.2

    - name: Set up Python ${{ matrix.pyversion }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.pyversion }}
        architecture: ${{ matrix.arch }}

    - name: Install deps
      run: |
        python -m pip install -U pip
        python -m pip install -U wheel requests numpy

    - name: Build the wheel and install it
      run: |
        python setup.py build -j4 bdist_wheel
        python -m pip install --ignore-installed --pre --no-index --find-links=dist/ pygame

    - name: Run tests
      env:
        SDL_VIDEODRIVER: "dummy"
        SDL_AUDIODRIVER: "disk"
      run: python -m pygame.tests -v --exclude opengl,timing --time_out 300

    # We upload the generated files under github actions assets
    - name: Upload dist
      uses: actions/upload-artifact@v2
      with:
        path: dist/*.whl

#   - name: Upload binaries to Github Releases
#     if: github.event_name == 'release'
#     uses: svenstaro/upload-release-action@v2
#     with:
#       repo_token: ${{ secrets.GITHUB_TOKEN }}
#       file: dist/*.whl
#       tag: ${{ github.ref }}
#
#   - name: Upload binaries to PyPI
#     if: github.event_name == 'release'
#     env:
#      TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
#      TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
#     run: |
#       python3 -m pip install twine
#       twine upload dist/*.whl
